spacetelescope/stsci.tools

lib/stsci/tools/convertlog.py, lib/stsci/tools/fileutil.py, lib/stsci/tools/iterfile.py, lib/stsci/tools/logutil.py, scripts/convertlog, setup.cfg
=> Opus 2015 3dms

lib/stsci/tools/capable.py
Update version number, as an aid to double-check our build-test infrastructure.
=> update version number

lib/stsci/tools/capable.py, lib/stsci/tools/clipboard_helper.py, lib/stsci/tools/dialog.py, lib/stsci/tools/editpar.py, lib/stsci/tools/eparoption.py, lib/stsci/tools/filedlg.py, lib/stsci/tools/irafutils.py, lib/stsci/tools/listdlg.py, lib/stsci/tools/teal.py, lib/stsci/tools/tkrotext.py
change Tkinter imports to handle all possible 2to3 cases:
- 1) not done at all,
- 2) done but to imports only (as in original plan)
- 3) done to every place found in code (apparent current case)
=> change Tkinter import/usage (again) for Py3

lib/stsci/tools/convertwaiveredfits.py
This fixes a failing drizzlepac test with WFPC2 data.
=> correctly update header keyword

lib/stsci/tools/convertgeis.py, lib/stsci/tools/swapgeis.py
@stsci-hack Please review this PR
EDIT: Fix #17
=> Fix broken code due to removed 'new_table()' from astropy.io.fits

lib/stsci/tools/bitmask.py
This PR improves performance and reliability of the code.
NOTE: default type of the returned mask was changed from ``numpy.uint8`` to ``numpy.bool_``
=> Performance and reliability improvements. Change default returned mask type.

setup.cfg
=> 3.4.5 -> 3.4.6

setup.cfg
=> Bump version 3.4.10 -> 3.4.11

.gitignore, lib/stsci/tools/fileutil.py
Change the type of some input parameters from ``int`` (0 or 1) to ``bool`` in ``fileutil``. Update documentation accordingly.
=> Change int to bool in fileutil

lib/stsci/tools/tests/test_bitmask.py, setup.cfg, setup.py
This PR adds unit tests for the `bitmask` module in the `stsci.tools` package.
=> Add unit tests for bitmask module

.gitignore, .gitmodules, .travis.yml, setup.cfg, setup.py
=> TST: Add egg_info tests back to Travis CI

.rtd-environment.yml, README.md, doc/source/analysis.rst, doc/source/conf.py, doc/source/stpyfits.rst, doc/source/teal_guide.rst, lib/stsci/tools/convertwaiveredfits.py, readthedocs.yml, setup.cfg
=> DOC: RTD setup 

setup.cfg, setup.py
https://docs.pytest.org/en/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner
=> Reorganize pytest-runner to match recommended method.

.travis.yml, conftest.py, lib/stsci/tools/bitmask.py, lib/stsci/tools/irafutils.py
Update test matrix and add dependency versions in test header.
=> Update test matrix

CHANGES.rst
Adds a change log to the package to document changes in each version.
=> Adding change log starting with v3.6.0

.travis.yml, lib/stsci/tools/configobj.py, setup.cfg
=> TST: Fix CI failures

.gitignore, .gitmodules, CHANGES.rst, MANIFEST.in, doc/source/teal_guide.rst, lib/stsci/tools/__init__.py, lib/stsci/tools/versioninfo.py, setup.cfg, setup.py
=> MNT: Remove relic, use setuptools_scm

.bandit.yaml, .travis.yml, lib/stsci/tools/capable.py, lib/stsci/tools/cfgpars.py, lib/stsci/tools/convertlog.py, lib/stsci/tools/convertwaiveredfits.py, lib/stsci/tools/editpar.py, lib/stsci/tools/filedlg.py, lib/stsci/tools/irafutils.py, lib/stsci/tools/iterfile.py, lib/stsci/tools/mputil.py, lib/stsci/tools/nmpfit.py, lib/stsci/tools/teal.py, lib/stsci/tools/vtor_checks.py, setup.cfg
Same as #112 . Had to re-open as new PR due to GitHub server issue.
=> MNT: Add security scan and fix violations

.travis.yml
Similar to spacetelescope/acstools#135
=> MNT: Replace pep517 with python-build

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md, .github/labeler.yml, .github/workflows/ci_workflows.yml, .github/workflows/codeql-analysis.yml, .github/workflows/open_actions.yml
Add templates and upgrade workflows.
=> TST: Add templates and upgrade workflows

.github/workflows/ci_workflows.yml, .github/workflows/codeql-analysis.yml
This pull request is to allow skipping CI without fail.
=> TST: Skip CI no fail 

lib/stsci/tools/tests/test_breadcrumb.py, lib/stsci/tools/tests/test_cfgobj.py, lib/stsci/tools/tests/test_check_files.py, lib/stsci/tools/tests/test_compmixin.py, lib/stsci/tools/tests/test_irafutils.py, lib/stsci/tools/tests/test_isfits.py, lib/stsci/tools/tests/test_minmatch.py, lib/stsci/tools/tests/test_mputil.py, lib/stsci/tools/tests/test_stpyfits.py, lib/stsci/tools/tests/test_tkrotext.py, lib/stsci/tools/tests/test_xyinterp.py
=> Use absolute imports instead of relarive in unit tests

lib/stsci/tools/bitmask.py
Minor comments (changes) updates and "version" info in `bitmask` module.
EDIT: Direct follow-up of #136
=> Update comments in bitmask

lib/stsci/tools/tests/test_mputil.py
This enhances existing test to try to pass a complicated object (`HDUList`) to processes when using various start methods.
=> Enhance mputil test to use different start methods

setup.cfg
This pull request updates astropy min version to 5.0.4
=> Update astropy min version to 5.0.4

.github/workflows/ci_workflows.yml, .github/workflows/predeps_workflow.yml, lib/stsci/tools/tests/__init__.py, lib/stsci/tools/tests/test_isfits.py, lib/stsci/tools/tests/test_minmatch.py, lib/stsci/tools/tests/test_stpyfits.py
This pull request is to add on-demand workflow for RC testing and also updating existing.
=> TST: Add RC testing workflow and update exiting

.github/workflows/ci_workflows.yml, .github/workflows/codeql-analysis.yml, .github/workflows/predeps_workflow.yml, .readthedocs.yml, doc/source/conf.py, setup.cfg
This pull request is to make things work again.
=> Fix RTD and modernize workflows

.github/workflows/ci_workflows.yml, lib/stsci/tools/bitmask.py, lib/stsci/tools/tests/test_bitmask.py
Same reason as https://github.com/spacetelescope/reftools/pull/60
=> TST: numpy 2, python 3.12

setup.cfg
=> RTD: Sphinx 8 works

.github/workflows/ci_workflows.yml, lib/stsci/tools/linefit.py, setup.cfg
This pull request is to fix devdeps failure.
xref https://github.com/astropy/astropy/issues/15638
=> TST: Fix devdeps

lib/stsci/tools/editpar.py, lib/stsci/tools/vtor_checks.py
This pull request is to address ...
Fixes #<Issue Number>
=> Remove unused modules

.github/workflows/ci_workflows.yml, CHANGES.rst, lib/stsci/tools/asnutil.py
This pull request is to fix #169
=> MNT: asnutil numpy 2 compatibility

.github/workflows/ci_workflows.yml, pyproject.toml
the lowest Python version required supported by downstream dependencies is `>=3.9` in `calcos`
https://github.com/spacetelescope/stsci.tools/pull/173#issuecomment-2839876838
=> bump required Python version to 3.9

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/codeql-analysis.yml
This pull request is to address ...
Fixes #<Issue Number>
=> Rename master to main
