lib/stsci/tools/nmpfit.py
This should address https://github.com/spacetelescope/stsci.tools/issues/4
=> A simple stop-gap fix to read-only numpy.diagonal arrays

lib/stsci/tools/asnutil.py, lib/stsci/tools/convertlog.py, lib/stsci/tools/convertwaiveredfits.py, lib/stsci/tools/fileutil.py, lib/stsci/tools/tests/testStpyfits.py
The ``clobber`` parameter in ``astropy.io.fits`` write functions has been deprecated and it has been replaced with ``overwrite``: see https://github.com/astropy/astropy/pull/5171.
This has caused our code (see, e.g., ``drizzlepac`` - https://github.com/spacetelescope/drizzlepac/issues/15) to issue numerous deprecation warnings.
This PR updates the code in ``stsci.tools`` so that it uses ``overwrite`` for versions of astropy  >= 1.3 and ``clobber`` for verions < 1.3 (for backward compatibility).
=> Fix deprecated 'clobber' parameter in astropy.io.fits write functions

lib/stsci/tools/bitmask.py
Documentation for ``bitmask2mask()`` should use ``good_mask_value`` parameter instead of ``good_pix_value``.
=> Correct docstring for bitmask2mask

lib/stsci/tools/check_files.py, setup.cfg
When ``astrodrizzle``'s input image is a STIS ASN image ("multi-imset STIS ``_flt`` files"), IVM file list created by ``checkStisFiles()`` does not have correct format which leads to crashes in ``AstroDrizzle``.
This PR fixes IVM list bug for STIS.
However, since https://trac.stsci.edu/ssb/stsci_python/ticket/1217, users will have to unpack multi-imset STIS ``_flt`` files themselves because ``AstroDrizzle`` no longer runs ``updatewcs`` on input images.
CC: @stsci-hack
=> Fix a bug in handling IVM lists for STIS images

lib/stsci/tools/convertgeis.py, lib/stsci/tools/filedlg.py, lib/stsci/tools/readgeis.py, lib/stsci/tools/swapgeis.py
A long time ago some fellows used to overwrite Python's built-in ``str`` type with string values. This was causing problems in ``drizzlepac`` (see, e.g., https://github.com/spacetelescope/drizzlepac/pull/55). This PR renames ``str`` **variable** to something else to avoid possible conflicts.
=> Don't overwrite ( or assign string values to the) built-in 'str' type

setup.cfg
Unfortunately, I tagged previous changes with 3.4.8 without bumping version in the ``setup.cfg``. Here I bump the version to 3.4.9 followed by a tag update to the same version.
=> update version to 3.4.9

lib/stsci/tools/stpyfits.py
This simple update to stpyfits addresses Issue #35 by replacing the call to io.fits.NumCode with the call to the BITPIX2DTYPE dict instead. 
Manual testing indicates this resolves the problem identified during pipeline testing. However, this needs to be reviewed by someone familiar with io.fits ( @jhunkeler ?) or someone who uses it for pipeline support ( @mcara ) before being merged into master.
=> Updated stpyfits to replace deprecated function NumCode

setup.cfg
Refers to https://github.com/spacetelescope/stsci.tools/pull/36
=> Bump version 3.4.9 -> 3.4.10

lib/stsci/tools/stpyfits.py
cc @stsci-hack
This PR disables lazy loading. With lazy loading enabled `with_stpyfits` fails to populate `ConstantValueHDU`s. The root cause still needs further investigation.
With lazy loading enabled:
```python
>>> from stsci.tools import stpyfits as sfits
>>> fimg = sfits.open('j9bc59wfq_raw.fits',mode='update')
>>> fimg.info()
Filename: j9bc59wfq_raw.fits
No.    Name         Type      Cards   Dimensions   Format
0  PRIMARY     PrimaryHDU     221   ()
1  SCI         ImageHDU       146   (200, 200)   int16
2  ERR         ImageHDU        58   ()
3  DQ          ImageHDU        50   ()
4  WCSCORR     BinTableHDU     59   7R x 24C   [40A, I, A, 24A, 24A, 24A, 24A, D, D, D, D, D, D, D, D, 24A, 24A, D, D, D, D, J, 40A, 128A]
>>> fimage[2].data
None
```
With lazy loading disabled:
```python …
```
=> stpyfits: disable lazy loading

lib/stsci/tools/stpyfits.py
Astropy 2.0.x removed `ImgCode` from `io.fits`. This change is backwards compatible with 1.3.x
=> Remove deprecated call to ImgCode

lib/stsci/tools/bitmask.py
@SaraOgaz reported that a deprecation warning for ``bitmask.bitmask2mask()`` incorrectly stated that users should use ``bitmask.flags_to_boolean_mask()`` - a non-existent function. The correct warning should point towards ``bitmask.bitfield_to_boolean_mask()``. This PR corrects the deprecation warning for ``bitmask.bitmask2mask()``.
=> Fix incorrect deprecation warning for bitmask.bitmask2mask

setup.cfg
This change prevents the following error:
```python
pkg_resources.DistributionNotFound: The 'stsci.distutils' distribution was not found and is required by stsci.tools
```
The `d2to1` and `stsci.distutils` dependencies are handled by `setup_requires` in `setup.py`, and should not be installed directly into the environment. This package does not use either, post-install. `setuptools` is not required either, because the installation is handled indirectly by `stsci.distutils`...
**stsci.distutils/setup.cfg:**
```ini
requires-dist = 
setuptools
d2to1 (>=0.2.5)
```
=> Remove build-time dependencies from run-time

lib/stsci/tools/bitmask.py
I was working on regression tests for the `bitmask` module when I have encountered a strange `OverflowError` that was happening *in some cases* when `ignore_flags` contained "too high" bits (for particular `bitfield` arguments).
Here are several examples:
```python
>>> from stsci.tools import bitmask
>>> import numpy as np
>>> bitmask.bitfield_to_boolean_mask([-1,0,1], np.uint64(1<<63))
array([False,  True, False], dtype=bool)
>>> 
>>> # ... but:
>>> bitmask.bitfield_to_boolean_mask([-1,0,1], [np.uint64(1<<63)]) # flag internally converted to int
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/.../stsci.tools/lib/stsci/tools/bitmask.py", line 412, in bitfield_to_boolean_mask
ignore_mask = np.bitwise_not(bitfield.dtype.type(ignore_mask))
OverflowError: Python …
```
=> Add support for large integer bit flags

lib/stsci/tools/bitmask.py
Unfortunately https://github.com/spacetelescope/stsci.tools/pull/56 did not completely fix the issue of very large flags compared to the number of bits supported by integer `numpy` types). This is an attempt to "close the hole" in the logic for filtering out high order bits.
=> Improve logic for filtering high bits in flags

.gitignore, lib/stsci/tools/convertgeis.py, lib/stsci/tools/readgeis.py, lib/stsci/tools/swapgeis.py, setup.cfg
Fix #59 .
It appears that `NumCode` was deprecated a long time ago in astropy/astropy#3916 and removed in astropy/astropy#4993.
**To test this branch**
It is recommended that you switch to a new `conda` environment to test this, which then you can delete when done:
```
conda install d2to1
conda install stsci.distutils
git clone https://github.com/pllim/stsci.tools.git
git checkout fix-geis-conv
python setup.py install
```
=> Fix GEIS modules

lib/stsci/tools/gfit.py, lib/stsci/tools/linefit.py, lib/stsci/tools/nmpfit.py
The goal is to remove this module. The only place it's used is in stistools.mktrace. It should be replaced with astropy.modeling. The two changes should be somewhat coordinated.
Fix #72
=> WIP: deprecate nmpfit

lib/stsci/tools/tests/test_minmatch.py
* Remove `mmd_keys` and `mmd_values` fixtures
* Replace `mmd_*` usage with `BASE*` variables
Fixes: https://github.com/spacetelescope/stsci.tools/issues/88
cc @nden
=> pytest 4.x: Refactor test_minmatch

lib/stsci/tools/check_files.py, lib/stsci/tools/fileutil.py, lib/stsci/tools/tests/test_check_files.py
This PR ensures that the conversion from waivered to mef FITS works with HDUList objects as well as file names.
=> convert waivered fits HDUList objects

lib/stsci/tools/check_files.py, lib/stsci/tools/fileutil.py
These changes allow the Drizzlepac tests to pass with the changes to STWCS which convert updatewcs to work with HDUList objects as inputs.  Specifically, the code which converts waiver FITS files (like WFPC2) was modified to be consistent with the HDUList inputs.
=> Fix stis kw

lib/stsci/tools/nmpfit.py
`nmpfit` shoul dhave been removed in this upcoming release. However the code in `stistools` that uses it has not been updated yet. Changing the deprecation warning to specify a later version of removal.
=> remove nmpfit in later versions

lib/stsci/tools/check_files.py, lib/stsci/tools/tests/test_check_files.py
The logic in check_exptime was setup to remove filenames from the input list.  However, the input list it now gets is always a list of HDUList objects, not filenames.  This code was therefore changed to try to remove the HDUList objects for exposures with exptime==0 instead of the filename.  This problem was identified in HSTDP 2019.2 regression testing, with the fix in this PR being tested against the dataset reported by HSTDP as well as another ASN where exptime was valid.
=> Fix logic in check_exptime

.gitignore, lib/stsci/tools/teal_bttn.py
Fixes a crash in TEAL when user attempts to load `MDRIZTAB` parameters in `astrodrizzle` but the `*_mdz.fits` file does not exist.
=> Fix crash in TEAL when loading MDRIZTAB parameters

lib/stsci/tools/irafutils.py
To avoid error in Python 3.8 and warnings in Python 3.6 and 3.7.
=> Use raw string in regex

setup.py
An incompatibility with io.fits was introduced in astropy v3.2 that can not be resolved in stsci.tools itself.  This simply insures that we do not use astropy v3.2 until a fix has been released in a new version of astropy.
=> Pin to astropy 3.1 to avoid io.fits incompatibility

.gitignore, lib/stsci/tools/stpyfits.py, setup.py
Fix #98. 
The approach I initially suggested cannot work because ones also need the data in the header modification code, which cannot be done inside the descriptor. 
So instead one solution - implemented here - is to monkey patch `_BasicHeader.fromfile` to force the loading of the full header. Not ideal  but at least it works for now, and if you need a better solution on the long term we can think about it.
cc @pllim
=> Fix ConstantValueHDUs to work with astropy 3.2

.gitignore, .readthedocs.yml, .rtd-environment.yml, .travis.yml, CHANGES.rst, MANIFEST.in, conftest.py, lib/stsci/tools/bitmask.py, lib/stsci/tools/irafutils.py, lib/stsci/tools/stpyfits.py, lib/stsci/tools/teal_bttn.py, readthedocs.yml, setup.py
This PR defines what would be released as part of the 'quick fix' release HSTDP-2019.3b as stsci.tools version 3.6.0.
=> Creating Release from 3.6.x

lib/stsci/tools/gfit.py, lib/stsci/tools/linefit.py, lib/stsci/tools/nmpfit.py, lib/stsci/tools/tests/test_bitmask.py
This replaces the deprecated Numpy globals
```python
np.float
np.int
```
with the Python types
```python
float
int
```
to avoid (reduce) deprecation warnings.
=> Use Python 'int' and 'float' type to avoid numpy warnings

CHANGES.rst, lib/stsci/tools/bitmask.py
Currently `numpy 1.21.1` raises an exception (should have been a deprecation warning) when running `bitmask` code due to the following change: https://numpy.org/doc/stable/release/1.21.0-notes.html#changes-to-dtype-and-signature-arguments-in-ufuncs. This PR improves compatibility with `numpy>=1.21.0`.
Also see https://github.com/numpy/numpy/issues/19625
This PR improves compatibility with `numpy 1.21.*`
=> Improve bitmask compatibility with numpy 1.21

CHANGES.rst, lib/stsci/tools/basicpar.py
Replacing `__dict__` in `__setstate__()` implicitly called `__setattr__`, which however hides the `__dict__` atribute from being set. To work around this, the method now instead updates the existing `__dict__` with the new values.
A trivial example (which replaces the `__dict__` with itself):
```python
from stsci.tools.basicpar import IrafParI
foo = IrafParI(['foo', 'i', 'h'])  # Create a simple integer IRAF variable
new_state = foo.__dict__.copy()    # Example dict that would be read in unpickle()
foo.__setstate__(new_state)        # This is called during unpickle()
```
Without this patch, this would give an exception:
```
File "…/stsci/tools/basicpar.py", line 589, in __setstate__
self.__dict__ = state
File "…/stsci/tools/basicpar.py", line 559, in __setattr__
raise AttributeError("No …
```
=> Fix unpickling of IrafPar

.github/workflows/build.yml
attempt to resolve build issues that prevent importing `stsci.tools` when installing from the wheel (https://github.com/spacetelescope/stsci.skypac/pull/72#issuecomment-2120503849)
```shell
❯ pip install stsci.tools
❯ python -c "import stsci.tools"
Traceback (most recent call last):
File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'stsci.tools'
```
closes #161
=> ensure module is present in built wheel

.github/workflows/ci_workflows.yml, lib/stsci/tools/tests/test_compmixin.py
This pull request is to fix #163
=> Adjust test for Python 3.13

.github/workflows/build.yml, .github/workflows/ci_workflows.yml, .github/workflows/codeql-analysis.yml, .github/workflows/open_actions.yml, .github/workflows/predeps_workflow.yml
As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)
=> MNT: Use hash for Action workflow versions and update if needed
